### ISSUE TITLE
You rock 🕺

### ISSUE THREAD

**Issue by mmlngl** [dangvanthanh/remix-turborepo-boilerplate#1]
Thanks for making this.

I struggled for a few days to make Remix play nice with turborepo

**Comment by dangvanthanh** [comment]
@mmmoli  Your welcome.

Currently, I am upgrading to React Router 7. It works well locally, but there are issues when deploying on Vercel. I will fix it soon.

**Comment by mmlngl** [comment]
> @mmmoli  Your welcome.
> 
> Currently, I am upgrading to React Router 7. It works well locally, but there are issues when deploying on Vercel. I will fix it soon.

No worries. I'm looking elsewhere for hosting these days. 

I've forked this to add my own personal flavour on top. Happy to merge back in if you think it's useful. 

For now though, I'll keep out of your way.

I dropped a star anyway and I've subscribed to updates 🍿👀
